# Generated by Django 4.2.7 on 2023-11-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_product_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
